title: "Taylor Nichols Quantitative Research"

description: >
  Algorithmic trading, machine learning, and quantitative finance research.

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "default"

search: true

author:
  name: "Taylor Nichols"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

exclude:
  - cv-source.md
